# Generated by Django 5.2.8 on 2025-11-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='name',
            new_name='nome',
        ),
    ]
