# Generated by Django 5.2.8 on 2025-11-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_rename_name_local_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsavel',
            old_name='name',
            new_name='nome',
        ),
    ]
